version: '3'

services:
  iredmail:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "25:25"
      - "80:80"
      - "110:110"
      - "143:143"
      - "443:443"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - ./config:/iRedMail-1.4.1/custom
    environment:
      - TZ=UTC
    restart: unless-stopped
